name: Go Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List repo root contents
        run: ls -la

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Install Dependencies
        run: go mod tidy
        working-directory: task_manager_Testing

      - name: Run Unit Tests
        run: go test ./... -v -coverprofile=coverage.out
        working-directory: task_manager_Testing

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: task_manager_Testing/coverage.out
